### ISSUE TITLE
Issues in `assembly.py`

### ISSUE THREAD

**Issue by padix-key** [BradyAJohnston/MolecularNodes#109]
Hi, I had a look at the code for building biological assemblies. Since I just implemented reading assemblies from PDB and MMTF myself in *Biotite* (see https://github.com/biotite-dev/biotite/pull/450 for reference), I think I spotted a few errors in `assembly.py` that I would like to report here.

1. As far as I understand the code, it does not parse the chains the transformations should be applied on. In my experience this is not an issue for most structures, but some structures use one set of transformations for some chains and another set of transformations for other chains (example: `5ZNG`).

2. The PDB parser parses assembly symmetry operations from `SMTRY` records in [Remark 290](https://www.wwpdb.org/documentation/file-format-content/format32/remarks1.html#REMARK%20290).
However this remark contains transformations to recreate atoms in the crystallographic unit cell, which do not necessarily represent the functional unit of the biomolecule. The transformations to create the assembly are stored in [REMARK 350](https://www.wwpdb.org/documentation/file-format-content/format33/remarks2.html#REMARK%20350) instead.

4. The PDBx parser assumes that each entry in the `pdbx_struct_oper_list` category gives the transformation for one copy in the assembly, as it is the case for PDB and MMTF. Unfortunately, the behavior for PDBx files is somewhat different: Which of these transformations must be applied is defined in the "oper_expression" category. Although for most structures this makes no difference in my experience, there are exceptions: Some assemblies may omit certain transformations, while other assemblies require even a Cartesian product of multiple transformations.

As far as I understand, the reason `assembly.py` is parsing the transformations instead of using `get_assembly()` from *Biotite* directly is for performance reasons in the rendering process, correct? If you specify what kind of information is required, I could contribute a PR by copy-pasting and adapting the code I wrote for *Biotite* for building assemblies.

I think the current `transform_dict` that the functions in `assembly.py` return are not able solve point 1 form the list above. So maybe another return value is required here? Alternatively, one could just say that cases, where point 1 applies are simply not covered.

**Comment by BradyAJohnston** [comment]
Hi mate, thanks for looking into it! The assemblies were high on my list of things to rework as I had only managed to get it reliably working for when importing from the RCSB via `mmtf` format, and yes even then it currently lumps all chains into the same transformations and only does it for the first biological assembly in the file rather than supporting later ones (laziness on my part when getting it set up).

I likely think the whole approach needs an overhaul, and would be very excited to have contributions on it!

The reason I don't use `get_assembly()` is yes for performance reasons. I could instantiate all of the atoms for the entire biological assembly and then add all of those to Blender, but it's more performant to instead leverage instancing inside of Blender for CPU & GPU performance in Geometry Nodes and on render time.

The information that I need to achieve the instancing is a Euler rotation and a Translation. The Euler I convert the rotation matrix to inside of Blender but have realised that I can do that on import using SciPy instead. Additionally, information on selecting which chains to use would need to be in the form of an integer array. Geometry Nodes currently only accepts numerical data, so I convert all of the `chain_id`s to integers based on their alphabetical ordering. For use internally in Blender, an iterable that has the assembly ID, translation, euler, and chains for each instance would be what I am after.

So as it stands the `pdbx` and `pdb` related functions in `assembly.py` aren't used and only the `mmtf` models imported via fetching from the PDB have biological assembly information that you can use to build inside of Blender. 
 
Would be very excited to have your contributions and feedback on this!

**Comment by padix-key** [comment]
Since all these files formats contain rotation matrices, I would suggest leaving the task of converting it into Euler angles up to you, since this would be same for each format. I would write three functions (one for each format) that return a dict that maps the assembly IDs to the necessary transformations for a set of chains. More specifically the return value would be
```
     assembly ID
     |    transformations on sets of chains for this assembly
     |    |          chain IDs affected by the transformation
     |    |          |        3x3 rotation matrix
     |    |          |        |        translation vector 
     |    |          |        |        |
dict[str, list[tuple[ndarray, ndarray, ndarray]]]
```

**Comment by BradyAJohnston** [comment]
That would be perfect for what I am after! From that I can build the required nodes programmatically for each structure when required. Open to your input on how you think it should be structured in terms of files & functions etc. You have a lot more python dev experience than I do!

**Comment by padix-key** [comment]
As I am currently working on this issue, I have two questions:

1. I would like to test my code against the result of `biotite.io.pdb.get_assembly()`. Is this possible, and if this is the case, how should I include tests?

2. As far as I see, *MolecularNodes* has no license file. To my understanding this means, that the copyright defaults to 'All rights reserved to the author of the code'. This would mean that any person may not change or distribute his copy of *MolecularNodes* without explicit permission from all contributors of *MolecularNodes*. If this behavior is intended you can ignore this remark, otherwise I would suggest adding a standard license of your choice to the project. To my knowledge you would also need permission from all existing authors to add an explicit license.

**Comment by BradyAJohnston** [comment]
Tests are something that I haven't yet added but certainly are in need of being added. I haven't done so yet because 1. I haven't unit tested before in Python and 2. a lot of the addon (everything regarding the nodes internally inside of Blender) are quite difficult to test for.

So far I have gotten away with it because I am just calling code from biotite and MDAnalysis which are both tested very rubstly. There is a need to add a testing framework though, and to try and extend this to some of the internal nodes inside of Blender. That part will be more difficult, but initial testing framework can certainly be set up. 

Regarding the license, I hadn't realised that I had accidentally deleted the license file when I was going through and refactoring the whole addon. I originally had the MIT license (https://github.com/BradyAJohnston/MolecularNodes/blob/cf0e1adc6cc9700de369e6e3b96cdeacf2554dd6/LICENSE), but managed to delete it a back in September without noticing. 

I'm not a licensing expert, so I'm not sure what that means in terms of license - any advice would be appreciated!

**Comment by padix-key** [comment]
> So far I have gotten away with it because I am just calling code from biotite and MDAnalysis which are both tested very rubstly. There is a need to add a testing framework though, and to try and extend this to some of the internal nodes inside of Blender. That part will be more difficult, but initial testing framework can certainly be set up.

I would suggest that I create a `tests` directory with a few test functions formatted for `pytest` for now. When you have picked a fitting test strategy for the entire project, you may adapt the code as you like.

> Regarding the license, I hadn't realised that I had accidentally deleted the license file when I was going through and refactoring the whole addon. I originally had the MIT license (https://github.com/BradyAJohnston/MolecularNodes/blob/cf0e1adc6cc9700de369e6e3b96cdeacf2554dd6/LICENSE), but managed to delete it a back in September without noticing.

I am not an expert either, I just read some articles on the internet. I would expect that you would just have to ask the contributors that added code after you removed the license, whether it is OK to release their code under the MIT license.

**Comment by BradyAJohnston** [comment]
If you could create a tests directory that would be a great start, and I can add more for more of the project as well. I'll ask the other contributors as well about the license, but I think they were all made before I deleted the license file. Will have to go back and check.

**Comment by BradyAJohnston** [comment]
There was one contribution #132 which had been added and I got the OK to re-add the MIT license so that has been added to the repo.
