### ISSUE TITLE
Numerical Representation of Atom Name

### ISSUE THREAD

**Issue by BradyAJohnston** [BradyAJohnston/MolecularNodes#118]
To enable features like secondary structure detection and cartoon representations of proteins and nucleic acids, having the atom name field as an attribute inside of MN / GN.

For some atoms this is currently hardcoded like `is_alpha_carbon` attribute field for alpha carbons, but this should be used more broadly so selections of particular parts of particular amino acids and molecules would be possible.

The question would be how to numerically encode this information. For example, an array of atom names `['C', 'O', 'C1, 'C']` could be alphabetically ranked and numerically encoded as `[0, 2, 1, 0]` for GN to understand it.

From looking into it briefly, I haven't been able to find a definitive list of which atom names are pre-defined and possible to be used. I assume that there is a common list for the 20 natural amino acids and the different nucleic acids, but then it could potentially be defined by users for more edge cases?

Looking at an example structure `6n2y`:
```python
import MolecularNodes as mn
import numpy as np
mol, file = mn.load.open_structure_rcsb('6n2y')
np.unique(mol.atom_name)
```
```python
array(['C', "C1'", 'C2', "C2'", "C3'", 'C4', "C4'", 'C5', "C5'", 'C6',
       'C8', 'CA', 'CB', 'CD', 'CD1', 'CD2', 'CE', 'CE1', 'CE2', 'CE3',
       'CG', 'CG1', 'CG2', 'CH2', 'CZ', 'CZ2', 'CZ3', 'MG', 'N', 'N1',
       'N3', 'N6', 'N7', 'N9', 'ND1', 'ND2', 'NE', 'NE1', 'NE2', 'NH1',
       'NH2', 'NZ', 'O', 'O1', 'O1A', 'O1B', 'O1G', 'O2', "O2'", 'O2A',
       'O2B', 'O2G', 'O3', "O3'", 'O3A', 'O3B', 'O3G', 'O4', "O4'", "O5'",
       'OD1', 'OD2', 'OE1', 'OE2', 'OG', 'OG1', 'OH', 'P', 'PA', 'PB',
       'PG', 'SD', 'SG'], dtype='<U6')
```

One could use a set of some amount to generate a list to work from. If you then have that list - how do you order it? 
So far I have just been encoding things in alphabetical order which I believe works well for amino acids. For these atom names however Having `O` so far down the list seems wrong, and I feel like the backbone atoms should be listed first. This could potentially make it easier to work with from a human perspective when having to manually define nodes inside of Blender to work with the numerical representations of these atom names. If you order the backbone atom names higher, should you also apply a level of order to the other atom names as well? If you end up with atom names which weren't accounted for, then where will they fall within the ordering?

I would love any feedback or comments on the matter. Unfortunately, this will have to be somewhat hardcoded inside the nodes themselves, so updating will be tricky and a logical implementation the first time will be ideal.

**Comment by at-ray-o** [comment]
How about doing it like this: prioritize ordering by number of letters first, and then alphabetically. So atoms with less number of letters will go first. Atoms with same number of letters will go alphabetically.
This way you will always put the CNOP at the top, followed by C1 C2 O1 etc. Then there will be the CG1 OD2 etc.

**Comment by cbouy** [comment]
Hi Brady,

For a list of atom names currently in use in the PDB, you can look at the **Chemical Component Dictionary (CCD)** it contains some info that might be interesting for your use case. Example here for [PHE](https://www.ebi.ac.uk/pdbe-srv/pdbechem/atom/list/PHE). You can also download the whole (quite big) mmCIF file on [this page](https://www.wwpdb.org/data/ccd) to try and parse it automatically. It also holds the SMILES repr of all residues in the PDB so you could go pretty far in terms of atom properties supported...

For the numerical encoding of atoms, that can be done using a **hash function** given a list of properties. Now I'm not sure I understand why you would need to sort them logically or have them be a continuous set of integers to allow users to do more exotic selections based on atomic properties?

Let's say you define the following properties for each atom:
```python
from typing import Dict, NamedTuple

class AtomProp(NamedTuple):
    element: str
    backbone: bool
    aromatic: bool
    charge: int
    stereo: str
```
Some examples for PHE atoms:
```python
CA = AtomProp(
    element="C",
    backbone=True,
    aromatic=False,
    charge=0,
    stereo="S"
)
CG = AtomProp(
    element="C",
    backbone=False,
    aromatic=True,
    charge=0,
    stereo="UNDEFINED"
)
CE1 = AtomProp(
    element="C",
    backbone=False,
    aromatic=True,
    charge=0,
    stereo="UNDEFINED"
)
```
You can use any hash function to convert these atom property objects to an int. Here using the standard Python `hash` function:
```python
>>> hash(CG)
-7 585 838 269 183 328 292
```
In this example, because CG and CE1 hold the same values in the AtomProp tuple, they would map to the same integer. If that's not wanted, you could add the atom name as a property as well. Also the fact that it maps to an integer is not really important, it could map to a string (hexdigest-like) and it would be fine. And each atom node in MN would just hold this value instead of one atom property as an attribute.

Then you could use a lookup table that maps all the hash values encountered for the currently loaded molecule to the properties, and define a function that uses this lookup table to perform atom selection solely base on the atom-hash:
```python
# this would be populated as you read the input file
atom_lookup: Dict[int, AtomProp] = {
    hash_func(atom_prop): atom_prop
    for atom_prop in [CA, CG, CE1]
}

def is_neutral_sidechain(atom_id: int) -> bool:
    props = atom_lookup[atom_id]
    return (props.charge == 0) and (not props.backbone)
```

Not sure how this would play with the MN/GN code, or if I'm clear!

Cedric

**Comment by PlethoraChutney** [comment]
## If it were up to me,
I'd encode them as

$$10\ 000 \times ord(u) + 100 \times ord(v) + ord(w)$$
where your three-letter atom code is split into _u_, _v_, and _w_. These have to  be uppercase, since `ord('d') == 100`

```
In [1]: def atom_to_int(atom_name):
   ...:     return int(''.join(str(ord(x)) for x in atom_name.ljust(3)))
   ...:

In [2]: atom_to_int('CA')
Out[2]: 676532
```

It's not necessarily human-readable, but you'd learn pretty quickly what's what. For instance, just in writing that function I doubt I'd quickly forget that 67 is C and 32 is space. It doesn't satisfy your sorting requirement though, since sorting by `ord(x)` is more or less the same as sorting by `x`.

## But if you want a single, sortable int

I think your intuition that it would be important to encode backbone atoms with low integers is correct, but I'm struggling to think of a system to help you do that. One thing you could consider is an $A(N + 1) + B$ encoding, where A is some integer for the element (perhaps lower A values awarded to elements which appear more often in general), N is the distance from the backbone, and B is some fudge factor to deal with rings and other symmetries.

Some examples:

Let's set A for some common elements: 103 for C, 157 for N, and 197 for O. I'm setting these as primes because we'd like to avoid collisions, where possible. Ideally we could use 1, 2, 3, etc., but we'd immediately run into a collision between C and N (or O, depending on which one got A = 2). This is already getting away from your desire to be human legible, but it is systematic.

CA is C, distance 0 from the backbone, giving encoding $103(0 + 1) + 0 = 103$. Similarly, N is 157 and O is 197.

In Ile, we've got the following atom names:

- CA = 103
- C = 104 (our first use of B, setting it to 1, since both CA and C are distance 0 from the backbone)
- O = 197
- CB = 206
- CG1 = 309
- CG2 = 310
- CD1 = 412

Eventually you'll hit collisions, but it would number stuff okay. And importantly, you're now able to sort and get all your backbone atoms at the beginning of the list. You would definitely need a lookup table for the A constants, though.

**Comment by BradyAJohnston** [comment]
Thanks for the info @cbouy ! A hash function could be useful. Certainly if I want the IDs to be unique then using a 'proper' hash function or a similar one to what @PlethoraChutney has proposed could be useful. 

What I'm really after is a single list, or 'lookup table' that will be useful internally inside of MN for IDing atoms for particular purposes.

The second suggestion @PlethoraChutney would be workable. I think regardless of what I do I'll have to end up with some time of reference table that I will have to work from. 

It doesn't necessarily need to be a procedurally applied function to a specific atom name. What I'm really after is that given say the most common atom names that appear in the 20 amino acids (and nucleic acids & sugars) such as: 

```python
array(['C', "C1'", 'C2', "C2'", "C3'", 'C4', "C4'", 'C5', "C5'", 'C6',
       'C8', 'CA', 'CB', 'CD', 'CD1', 'CD2', 'CE', 'CE1', 'CE2', 'CE3',
       'CG', 'CG1', 'CG2', 'CH2', 'CZ', 'CZ2', 'CZ3', 'MG', 'N', 'N1',
       'N3', 'N6', 'N7', 'N9', 'ND1', 'ND2', 'NE', 'NE1', 'NE2', 'NH1',
       'NH2', 'NZ', 'O', 'O1', 'O1A', 'O1B', 'O1G', 'O2', "O2'", 'O2A',
       'O2B', 'O2G', 'O3', "O3'", 'O3A', 'O3B', 'O3G', 'O4', "O4'", "O5'",
       'OD1', 'OD2', 'OE1', 'OE2', 'OG', 'OG1', 'OH', 'P', 'PA', 'PB',
       'PG', 'SD', 'SG'], dtype='<U6')
```

How should these be ordered numerically, so as to be logical but also workable? Anything more fringe with the atom names that appear can usually be thrown away, as it's really only the primary atoms that I am maybe looking to utilise and these important that they are encoded numerically.

**Comment by BradyAJohnston** [comment]
AlphaFold has a _kind of_ similar encoding though not quite. Could take some of those ideas potentially and use them here:

https://github.com/deepmind/alphafold/blob/569eb4fea3733b979cb0442750b875759dd5ecc0/alphafold/common/residue_constants.py#L492-L496

```python
atom_types = [
    'N', 'CA', 'C', 'CB', 'O', 'CG', 'CG1', 'CG2', 'OG', 'OG1', 'SG', 'CD',
    'CD1', 'CD2', 'ND1', 'ND2', 'OD1', 'OD2', 'SD', 'CE', 'CE1', 'CE2', 'CE3',
    'NE', 'NE1', 'NE2', 'OE1', 'OE2', 'CH2', 'NH1', 'NH2', 'OH', 'CZ', 'CZ2',
    'CZ3', 'NZ', 'OXT'
]
```

**Comment by BradyAJohnston** [comment]
This is now initially implemented here: 
https://github.com/BradyAJohnston/MolecularNodes/blob/f866a21a8b642787c09427b2528e53c346210593/MolecularNodes/data.py#L814-L885

I have set the backbone atoms to be `1:4`, and then everything mostly following the ordering from the previous post which is used internally for AlphaFold. For the nucleic acids, currently only the backbone sugar-phosephate and a couple of the key atoms are implemented that are required for creating the ribbon / cartoon representation of the nucleic acid.

The other atoms reuse their names which messes with the ordering. I am unsure how to order them, but also I have no immediate use for them either. 

I initially wanted the atom names to reimplement the 'Wiggle' node, which is done (and ~3x faster) as well as the nucleic acid secondary structure.

Open to suggestions to how this could be done better or changed, but for now at least it seems to be working OK.

**Comment by BradyAJohnston** [comment]
I'm going to close the issue for now to clear out the issue tracker, but still welcome discussion / feedback either here on in the discussion tab.
