### ISSUE TITLE
Split bond nt working for local PDB file

### ISSUE THREAD

**Issue by RYG81** [BradyAJohnston/MolecularNodes#176]
**Describe the bug**
I have generated PDB file suing SMILES from here  - https://www.novoprolabs.com/tools/smiles2pdb
SMILE - O=C(O)C(N)CC(=[N@H])O
Then I export out put as pdb file

**To Reproduce**
1. Go to 'https://www.novoprolabs.com/tools/smiles2pdb.'
2. Set SMILE = O=C(O)C(N)CC(=[N@H])O
3. Click on 'Submit'
4. Select output format  - pdb
5. Click on 'download 3d model'
6. Import as local file in Blender Molecular node UI and oad model as Ball and Stick Style

**Expected behavior**
On selecting split bond it should convert two C-O bonds to double bond but unfortunately it is not working.

**Error Codes**
NONE
# paste error codes from python console hereNONE

**Screenshots**

![image](https://user-images.githubusercontent.com/10570236/224715804-7bd7be7c-dfcf-4f25-ab8b-e2e66ba7c02d.png)

![image](https://user-images.githubusercontent.com/10570236/224716442-3e7e387e-f097-49ea-8139-45950b9527b1.png)

Double bonds missing

**Desktop (please complete the following information):**
 - Windows ]
 - Intel  x64 PC]
 - Blender Version: 3.4.1
- MolecularNodes Version: 2.4.1

**Additional context**

Also is it possible to have custom geometry option where I can choose different model for bonds?

Thanks for making such amazing addon.
Rahul

**Comment by BradyAJohnston** [comment]
Thanks for the bug report! I've had a quick play around and it seems like it might be a bug with `biotite` itself which is the python package which powers the majority of the `.pdb` file parsing. The following example code with the example PDB shows the underlying bonds are all generic single bonds. I'll open up an issue in the bitoite repo.

### Example PDB
```
HETATM    1  O1  UNL     1      -1.096   2.063  -0.154  1.00  0.00           O  
HETATM    2  C1  UNL     1      -0.206   1.429   0.476  1.00  0.00           C  
HETATM    3  O2  UNL     1      -0.170   1.483   1.866  1.00  0.00           O  
HETATM    4  C2  UNL     1       0.815   0.606  -0.268  1.00  0.00           C  
HETATM    5  N1  UNL     1       1.595   1.447  -1.178  1.00  0.00           N  
HETATM    6  C3  UNL     1       0.150  -0.537  -1.054  1.00  0.00           C  
HETATM    7  C4  UNL     1      -0.532  -1.523  -0.139  1.00  0.00           C  
HETATM    8  N2  UNL     1      -1.821  -1.644  -0.133  1.00  0.00           N  
HETATM    9  O3  UNL     1       0.225  -2.325   0.712  1.00  0.00           O  
HETATM   10  H1  UNL     1      -0.851   2.027   2.382  1.00  0.00           H  
HETATM   11  H2  UNL     1       1.519   0.162   0.472  1.00  0.00           H  
HETATM   12  H3  UNL     1       0.951   1.930  -1.848  1.00  0.00           H  
HETATM   13  H4  UNL     1       2.078   2.188  -0.620  1.00  0.00           H  
HETATM   14  H5  UNL     1       0.923  -1.082  -1.637  1.00  0.00           H  
HETATM   15  H6  UNL     1      -0.574  -0.115  -1.786  1.00  0.00           H  
HETATM   16  H7  UNL     1      -2.437  -1.068  -0.750  1.00  0.00           H  
HETATM   17  H8  UNL     1       1.237  -2.275   0.719  1.00  0.00           H  
CONECT    1    2    2
CONECT    2    3    4
CONECT    3   10
CONECT    4    5    6   11
CONECT    5   12   13
CONECT    6    7   14   15
CONECT    7    8    8    9
CONECT    8   16
CONECT    9   17
END
```

### Example Code
```python
from biotite.structure.io import pdb

file = pdb.PDBFile.read("C:/Users/BradyJohnston/Downloads/J76zYg.pdb")
atoms = file.get_structure(include_bonds = True)
atoms.bonds.as_array()
```
```
array([[ 0,  1,  0],
       [ 1,  2,  0],
       [ 1,  3,  0],
       [ 2,  9,  0],
       [ 3,  4,  0],
       [ 3,  5,  0],
       [ 3, 10,  0],
       [ 4, 11,  0],
       [ 4, 12,  0],
       [ 5,  6,  0],
       [ 5, 13,  0],
       [ 5, 14,  0],
       [ 6,  7,  0],
       [ 6,  8,  0],
       [ 7, 15,  0],
       [ 8, 16,  0]], dtype=uint32)
```

**Comment by BradyAJohnston** [comment]
I chatted to the Biotite dev, and it's because `.pdb` files don't officially support including bond types. While the website has written duplicate bond entries to the `.pdb` file, these aren't officially supported as part of a `.pdb` file spec, so Biotite doesn't try to read that information in. 

If you can first convert it to `.cif` or `.mmtf` with the bond information included, then that will be able to be imported, but as it currently stands the bond types won't be imported when loading from a `.pdb` file.

**Comment by RYG81** [comment]
Tried to download .cif file from here also - https://www.ebi.ac.uk/pdbe-srv/pdbechem/chemicalCompound/show/ASN
but same error
Direct Link to file - https://www.ebi.ac.uk/pdbe/static/files/pdbechem_v2/ASN.cif

**Comment by padix-key** [comment]
The problem is that `biotite.structure.io.pdbx.get_structure()` which is used by *MolecularNodes* reads the data from the PDBx `atom_site` category, which works for all regular PDB entries and should work for macromolecular structure output from most software. However, the small molecules in the PDB store their atom data in the `chem_comp_atom` category, which is structured differently, hence the exception appears.

I imagine multiple possible solutions here:

1. *MolecularNodes* could call `connect_via_residue_names()` after reading structures from PDB. That would have the disadvantage, that special bonds, such as connections to glycans, would be overwritten by this method.
2. *MolecularNodes* could support also the MOL and SDF formats, which have proper support of bond orders.
3. *Biotite* could add some function `pdbx.get_ligand()` to allow reading atom data from the `chem_comp_atom` category. This is already implemented in https://github.com/biotite-dev/biotite-util/blob/master/datasets/create_residue_dataset.py for generation of the dataset for `biotite.structure.info.residue()`. Then *MolecularNodes* could check which category is present in the file and use `get_structure()` or `get_ligand()` accordingly.
4. *MolecularNodes* could implement ligand parsong directly by adapting the code in https://github.com/biotite-dev/biotite-util/blob/master/datasets/create_residue_dataset.py.

**Comment by BradyAJohnston** [comment]
Hi @padix-key that would be fabulous! Certainly an implementation inside of _Biotite_ that _MolecularNodes_ could then leverage would be best from my point of view. 

Would this `.get_ligand()` also extract ligand information from a structure where there is protein + ligand? I'm not that familiar with the `.cif` spec and how it would all be set out.

**Comment by padix-key** [comment]
Great. Then I will open an issue in *Biotite* for this feature.

> Would this `.get_ligand()` also extract ligand information from a structure where there is protein + ligand? I'm not that familiar with the `.cif` spec and how it would all be set out.

No, the typical macromolecular structures contain the entire atom information (protein and ligand) in the `atom_site` category and have no `chem_comp_atom` category. Hence, `get_structure()` would be used for such files.

**Comment by padix-key** [comment]
Hi, parsing ligands will be supported in the upcoming release via the `get_component()` method, implemented via https://github.com/biotite-dev/biotite/pull/468 .

**Comment by BradyAJohnston** [comment]
Excellent. Thanks so much @padix-key !

**Comment by BradyAJohnston** [comment]
I figured out a little workaround for people in the mean time. You can manually create  vertex group called `double_bond` and manually assign the atoms that are part of double bonds by highlighting them in edit mode and clicking 'Assign'. 

![image](https://github.com/BradyAJohnston/MolecularNodes/assets/36021261/ce478f2d-a91a-407f-84d7-dd86e799016c)


Then inside of the node tree, you can store the bond type `2` on the `edge` attribute to specify double bonds, if both atoms of an edge / bond are involved in a double bond (see the node tree for working example).



![image](https://github.com/BradyAJohnston/MolecularNodes/assets/36021261/150b725c-b88e-4493-997c-f38f67776865)

![image](https://github.com/BradyAJohnston/MolecularNodes/assets/36021261/6543f955-0ac0-47be-8f14-f5cf2b2ee31a)

This will then be used in the `MOL_style_ball_and_stick` node to split the bonds into double bonds.

**Comment by padix-key** [comment]
The new Biotite version with `get_component()` is now finally released

**Comment by BradyAJohnston** [comment]
ooh very exciting @padix-key thanks for putting it all together!

**Comment by BradyAJohnston** [comment]
Initial test and it works. 

![image](https://github.com/BradyAJohnston/MolecularNodes/assets/36021261/603e78ee-c88b-459c-a186-53630a03b73e)


@padix-key if there are both macromolecular structures and small-molecules inside of a structure, will both `pdbx.get_structure()` and `pdbx.get_component()` need to be used, and their `AtomArray`s combined?

**Comment by padix-key** [comment]
Usually when you have a macromolecular structure file with or without ligands (e.g. a downloaded 4-character PDB entry) you only need `pdbx.get_structure()`. `pdbx.get_component()` is only needed for the rather rarely used ligand-only files, that use the `chem_comp` category to describe the structure instead of `atom_site`. In either case you only need to call one function, a combination is not required.

**Comment by BradyAJohnston** [comment]
Thanks for the details @padix-key ! Really appreciate all of the support you give to this project :)
