### ISSUE TITLE
Why `Open`/`Download` and then `OK`? 

### ISSUE THREAD

**Issue by RodenLuo** [BradyAJohnston/MolecularNodes#18]
Hi Brady, 

What is the design purpose here to have one more confirmation click? (It seems to me a redundant clicking... Every time I was hoping to get the operation being performed right away and then realized I need to click again.)

![image](https://user-images.githubusercontent.com/8460424/167136142-2a0225f9-f700-4e52-9879-3166314edf58.png)

**Comment by BradyAJohnston** [comment]
The idea initially was that because it can be an operation that takes quite a long time, to double check with the user to open or download the file first.

This was more of a concern in the beginning when I was unsure about the performance of the addon, so I could certainly remove it in future versions given performance is less of a problem than I initially anticipated.

**Comment by BradyAJohnston** [comment]
Is now changed in the latest release: https://github.com/BradyAJohnston/MolecularNodes/releases/tag/v0.4.1
