### ISSUE TITLE
Updated tutorials

### ISSUE THREAD

**Issue by bgeiss1** [BradyAJohnston/MolecularNodes#183]
I've just started using Molecular Nodes and Blender , and MN is a great addon to Blender. However, I'm running into an issue as a beginner where the current version of MN (2.4.3) is significantly different than the version that the tutorials were created around (0.8) and I'm having some difficulties translating what I'm seeing in the videos with the 0.8 version to the current 2.4.3 version. The rapid evolution of the software is amazing, and I was wondering if you are planning on generating any updated tutorials with an updated version of the addon. 

Thanks for creating this software and providing it to the community!

**Comment by BradyAJohnston** [comment]
You are right in that there is quite a difference between the initial tutorials that I made and where the addon is at now. I have been meaning to make more tutorials, but I have been holding off because I don't want them to become obsolete as Blender & Molecular Nodes updates quite quickly, and they take a fair bit of work to make.

With the coming release of Blender 3.5, some changes inside of Geometry Nodes are coming that I have been waiting to also, so I do plan on remaining a bunch of those tutorials in the coming weeks with the release of Blender 3.5 next week.

We shall see how much time I have to put towards that though.

**Comment by bgeiss1** [comment]
Great, thank you for your response. I completely understand not wanting you tutorials to become obsolete too quickly, especially since you just made a bunch 8 months ago. For now I'll focus on better understanding the basics of blender and try to figure out how to export blender structures as .fbx files that Unity can recognize, as my end goal is to generate molecular structures using your package that I can use in Unity as game assets for some educational games I'm working on.

**Comment by BradyAJohnston** [comment]
Tracking updating of documentation in #404
