### ISSUE TITLE
Replace Random value with ColorRamp?

### ISSUE THREAD

**Issue by Knight680** [BradyAJohnston/MolecularNodes#195]
With MoleclarNodes 2.5.4, I noticed that defalt chain color controlled by random value. Do you think it's more convenient to use the ColorRamp node instead so that users can manually control the colors? Basic idea is normalized chain id (since colorramp only accept float from 0 to 1), then place n (n = number of chain) positions to colorramp so user can defined color for each chain by change colore on each pos.

I attached a figure for reference.
![Screenshot from 2023-04-17 16-44-24](https://user-images.githubusercontent.com/60581999/232607173-77b5cf87-db1f-4045-a7c5-d63fb8675f7e.png)

**Comment by BradyAJohnston** [comment]
There is a node that, if chain information is detected in the structure, allows you to manually select the colours by chain without having to fiddle with a ColorRamp:

![image](https://user-images.githubusercontent.com/36021261/232629107-0e2c2de9-bd62-42fd-9c89-e996e48bc978.png)

You can then colour the structure like so:

![image](https://user-images.githubusercontent.com/36021261/232629174-1347f1f5-504e-48f5-9852-6fb3756f918b.png)

As for whether or not this should be the default instead of a random colour node in the starting node tree. I have the starting node tree with a random colour to maybe try and demonstrate some of the Geometry Nodes fields ideah. If it would be much more convenient for users to have manual control over their chain colours to begin with, then I could change the defaults.

**Comment by Knight680** [comment]
Oh, I agree with that colors by chain is more strightforward. Thanks again for your outstanding work!
