### ISSUE TITLE
Secondary Structure Detection Fails Occasionally

### ISSUE THREAD

**Issue by BradyAJohnston** [BradyAJohnston/MolecularNodes#197]
I have found the secondary structure detection to not be accurate for some structures. An example are the beta sheets in [this tweet](https://twitter.com/bradyajohnston/status/1648641968803844097?s=20). I am unsure if this is the current implementation of the SS detection, or an underlying `biotite` issue which is currently responsible for SS detection. 

![image](https://user-images.githubusercontent.com/36021261/233055128-e3b6485d-4127-408e-94c7-25f34d391e96.png)

@OLaprevote would you be able to look in to this? Should be able to troubleshoot by colouring ribbons based on SS to see where it's not getting it correct. Example in tweet is 3AEH.

**Comment by OLaprevote** [comment]
I already saw this with other structures. I think it's a limitation from biotite itself, more precisely the algorithm they use for secondary structure detection (P-SEA) that is using only the dihedral angles to detect SS, contrary to DSSP which uses hydrogen bonds as well.

I see two ways out of this:
- Go the hardcore open-source warrior way and implement DSSP into biotite. Technically there is already a python [implementation of DSSP](https://github.com/ShintaroMinami/PyDSSP), actually containing two: calculations can be done with either numpy or pytorch. So the work would be mainly to port this to biotite. I would actually be willing to get this done as I think it would benefit the structural biology community as a whole in the long term, but I'd say if there is no hidden difficulty it's still a day work (+ doing the PR and getting it accepted).
- I think it was already suggested in an issue I can't find, but reading the secondary structure attribute out of the mmCIF file itself may be another way out. It's probably less tricky. Back then I chose not to go down this road so that any kind of file (+ eventually MD trajectories) could get the SSE, but, well, it can't hurt.

**Comment by OLaprevote** [comment]
Yup, just ran 3AEH_A into the [sse tutorial of biotite](https://www.biotite-python.org/examples/gallery/structure/transketolase_sse.html) and the problem definitely comes from the SS detection algorithm 🙃


![image](https://user-images.githubusercontent.com/25614796/233183340-29b6a732-4c3a-4aea-b4f3-5a0d90146622.png)

**Comment by BradyAJohnston** [comment]
We could also implement the SS detection algorithm inside of GeometryNodes itself. This might be slightly trickier, but if it can be done then each frame of an MD animation can have SS detection applied to it, or even if you deform a protein then you can update the SS.

**Comment by OLaprevote** [comment]
Implementing either P-SEA-like or DSSP-like algorithm in Blender Geometry Nodes would be… wow.
- P-SEA "only" requires to compute phi and psi. Given I could do a N->O vector it should be doable. I imagine drawing the right SS phi/psi regions could be the difficult part, though phi/psi "squares" at first may work.
- DSSP would be a bigger chunk of math to implement, with some fun matricial operations (pyDSSP detection is ~100 lines and quite clean). Let's just say I'm not sure it's doable in one full day of work x)
It's not just dynamics: it would easily be computed for lots of different cases, e.g. in the long run maybe allow people to "draw" proteins with secondary structures.

For MD, though, I have to make a case: it should also be possible to implement pyDSSP in MDAnalysis. Same argument than for biotite: it would be useful not just for MolecularNodes but for a broader community, and you having a cool & precise user case is a good nudge for this to happen. I would gladly do it but it may take a few months (you saw my handling of the SS attribute here).
Getting DSSP working in MDAnalysis was already a requested feature but the [only attempt to do so](https://github.com/MDAnalysis/mdanalysis/pull/2609) was getting a conda implementation of C++ DSSP code to work in there and it was deemed too impractical as it introduced way too many dependencies.

Anyways I'd say both projects are broader than just a quick bug fix. Do you think right now it would be easy to somehow allow to "paint" the protein backbone with SS attribute, so that users could quickly change a few amino-acids to the right SS when it's not to their convenience? (Which… could actually be really cool for lots of different applications)

**Comment by BradyAJohnston** [comment]
If possible, having DSSP (or something at least mostly approximating it) inside of geometry nodes would be great. Might not be possible until the `Index of Nearest` node comes in potentially 3.6.

Certainly in the short term, accessing the SS that is already stored in a file is likely the best option, rather than trying to re-compute it. I haven't looked into it for `biotite` or `MDAnalysis` to see if either readers give access to that information, but in theory it should be.

**Comment by BradyAJohnston** [comment]
Just had a go at implementing a purely Geometry Nodes implementation of DSSP and it actually works pretty well:

![image](https://user-images.githubusercontent.com/36021261/233541218-b22695a4-97c0-4dcf-9389-e31743e97aca.png)

Currently it detects helices (alpha and 3-10 helices) by using their hydrogen bonding, then beta-strands based on their angles. This doesn't check at all for hydrogen bonding of the beta-sheets. I think that will be a limitation until 3.6 and more nodes come along. Seems to work 'well enough' on the structures that I have tested though. Given this is purely for visualisation, I'm less determined to get it 100% accurate. 

I think I would still much prefer to get access to the author-deposited SS from the file, but this can potential work for MD simulations and when there isn't SS available.

**Comment by BradyAJohnston** [comment]
I'm probably going to consider this solved for now as I implemented taking SS from the `mmtf` file when downloading from the PDB. The calculations will still fail a bit when opening a local file. The `MOL_utils_dssp` node will help in a lot of those cases and I will work on improving it also.

**Comment by tubiana** [comment]
I found a bug but it's coming from BIOTITE example and not for b-sheets...
They have classified `G` and `I` as coil instead of helices.
see here : https://github.com/BradyAJohnston/MolecularNodes/pull/203#issuecomment-1525694066

Cheers!
Thibault.
