### ISSUE TITLE
Backbone O selection is not correctly set

### ISSUE THREAD

**Issue by danpf** [BradyAJohnston/MolecularNodes#198]
Hi,
Currently `Backbone O` in `Mol_sel_res_atoms` is set via `is_backbone` and `atomic_number`.  However, biotite does not consider the `Backbone O` to be a backbone atom: https://github.com/biotite-dev/biotite/blob/786f13a672a601016574e1953ff0356e7e107e03/src/biotite/structure/filter.py#L43

you can fix this by replacing the backbone call with with `Named Attribute` : `atom_name` = 4

**Comment by BradyAJohnston** [comment]
Ah yes. I haven't updated `MOL_sel_res_atoms` since I implemented the `atom_name` attribute. I can update this to clean up a number of these nodes. I think I will also remove the `is_backbone` and `is_alpha_carbon` attribute, and instead replace it with selection nodes based on the `atom_name` as well. 

Biotite not selecting the O's for the backbone I believe is a deliberate choice, but for visualising I think it makes sense to include it so in changing the selection backend I will be updating all of that.
