### ISSUE TITLE
trajectory cannot be shown in cartoon style. 

### ISSUE THREAD

**Issue by luwei0917** [BradyAJohnston/MolecularNodes#244]
Thanks for the amazing work!

**Describe the bug**
Our protein trajectory can be shown in other style. But not in cartoon. Is this expected? 
Single static frame, could be shown in cartoon though.

Thanks.

**Comment by BradyAJohnston** [comment]
Hi @luwei0917 thanks for the kind words. 

At the moment, no secondary structure information is imported when importing a trajectory via MDAnalysis, thus the cartoon style doesn't show anything.

It sounds like the secondary structure is properly imported when just opening via `Local File` tab which then opens it via `biotite` instead of `MDAnalysis`.

You could potentially transfer the secondary structure data from the model that works as discussed in [this thread](https://github.com/BradyAJohnston/MolecularNodes/discussions/231). 

There is also a `MOL_utils_dssp` node which will do some secondary structure detection (not as accurate but probably 90% correct) however I have just realised that there is a bug with this node and I will have to release an update to fix it.

**Comment by kailinguo24** [comment]
Hi Brady,

I'm also trying to do the cartoon on MD thing, and I've tried to replicate your "store secondary structure attribute and then use that for the MD sim" thing from #231, but it's not working. Could you take a look at my node tree for the MD trajectory and see if I've done something horribly wrong, or if it's just doesn't work? I've imported frame 0 of the sim as a local file, so everything in the pdbs should line up well. It does still show up in atoms view, just not cartoon view. 
![image](https://github.com/BradyAJohnston/MolecularNodes/assets/116903309/cb322747-15a8-4801-b545-e26488918e16)

Thanks!

**Comment by BradyAJohnston** [comment]
Hi @kailinguo24 the structure mostly looks correct. For the object `MD_struct` do you have any styles applied? It will only work if the number of vertices etc are the same, so it's best not to have any nodes in the node tree on that object to ensure you are getting the underlying atomic data. It's a little finnicky, but that's currently all that I can think of that might be causing this to not work.

**Comment by kailinguo24** [comment]
Nope, MD_struct was in cycles atoms, and even if I put geometry -> geometry without anything in between, it still doesn't show up as cartoon in the MD trajectory. Thanks anyway!

**Comment by BradyAJohnston** [comment]
@kailinguo24 if you can share some example data (some frames and the topology etc) I can have a play around and see if I can get it working

**Comment by kailinguo24** [comment]
Hi Brady, it's actually not my data (provided by a coworker), so I'm not at liberty to share unfortunately. Thank you for the offer though, I really appreciate it!

**Comment by BradyAJohnston** [comment]
@kailinguo24 if you share the node tree of the `MD_struct` and maybe a screenshot of the data spreadsheet and I might be able to help. Otherwise best of luck!
