### ISSUE TITLE
Large PDB Import and No Chain ID Selection for Imported Trajectory

### ISSUE THREAD

**Issue by klmcguire** [BradyAJohnston/MolecularNodes#251]
**Describe the bug**

Issue #1) I have a PDB with more than 99,999 atoms.  Since I use VMD/NAMD the other atoms get named with the hybrid-36 format.  When I try to load this PDB using Local File, I get the error shown in the first image.

Issue #2) If I try to load an MD trajectory (DCD format) and a topology file (PSF format) I can see the animation and that works fine.  But I'm trying to change the representation and color of different parts of my system.  For example, I ran a quick simulation of just a lipid bilayer in water and ions.  I don't see a way to remove the waters and ions (or at least make them invisible) and just select the lipids so I can play around with their style and coloring.  I tried using the chainID selection node, but I get the error shown in the second image.

How do I fix both of these issues? Should I be loading a different topology file instead of the PSF? I can send files if you need them. Thanks!

![image](https://github.com/BradyAJohnston/MolecularNodes/assets/105521635/c3529920-6947-4016-81c1-60a476af2bf9)

![image](https://github.com/BradyAJohnston/MolecularNodes/assets/105521635/86f81ba8-335f-4e6f-9792-d6d3ec8a2749)

**Desktop (please complete the following information):** 
 - OS: Windows
 - Hardware: x86 PC
 - Blender Version: 3.5.1
- MolecularNodes Version: 2.7.3

**Comment by BradyAJohnston** [comment]
>Issue https://github.com/BradyAJohnston/MolecularNodes/issues/1) I have a PDB with more than 99,999 atoms. Since I use VMD/NAMD the other atoms get named with the hybrid-36 format. When I try to load this PDB using Local File, I get the error shown in the first image.

For opening the local files, the parsing is handled by [`biotite`](biotite-python.org/) so there isn't much I can likely help with. Having atom counts that large inside of `.pdb` isn't officially supported so I would think it might remain an issue unless you switched to `mmCIF` formats whch are better designed for the larger files. 

You could try and use the `.pdb` parser from `MDAnlaysis`, which you can use if you just specify the toplogy file and not the trajectory. May or may not run into the same issue:

![image](https://github.com/BradyAJohnston/MolecularNodes/assets/36021261/dbc4c2aa-9129-4769-91c7-1e40e883c9c5)

>Issue https://github.com/BradyAJohnston/MolecularNodes/issues/2) If I try to load an MD trajectory (DCD format) and a topology file (PSF format) I can see the animation and that works fine. But I'm trying to change the representation and color of different parts of my system. For example, I ran a quick simulation of just a lipid bilayer in water and ions. I don't see a way to remove the waters and ions (or at least make them invisible) and just select the lipids so I can play around with their style and coloring. I tried using the chainID selection node, but I get the error shown in the second image.

`MDAnalysis` is used for importing toplogies and trajectories. You can check the [`MDAnalysis` docs](https://userguide.mdanalysis.org/stable/formats/index.html) for what should be imported via the `.psf` formatl. 

`.psf` only supports the following attributes being read: 
> angles, bonds, charges, dihedrals, impropers, names, resnames

Which is why you can't use anything chain-specific as the attribute doesn't exist and isn't created.

Some of the attributes around solvent and peptides etc should be imported, but I haven't tested extensively with different systems so some attributes may or may not be created successfully.

You could create a series of `Custom Selections` when importing the structure. These will then appear on the system when it is imported as boolean `True / False` as to whether the atoms are part of these selections. 

Press the <kbd>+</kbd> icon to create a new selection. The `Attribute Name` will be the name that for the boolean attribute when it is applied to the structure. The `Selection String` will use the [MDAnlysis selection language](https://userguide.mdanalysis.org/stable/selections.html) to create the given selection.

With this you should be able to create the custom selections that you want. Note that this will be only be applied _when importing_ the trajectory, so you must create these selections before you import the structure and not afterwards.

![image](https://github.com/BradyAJohnston/MolecularNodes/assets/36021261/6a6a551f-ffa7-495d-88d9-eb115f1b236e)

Hopefully this helps a bit, but if you share the files I am happy to have a poke around and try and help out with getting what you are after. Certainly still room for improvement around the selections and attributes when importing via MDAnalysis.
