### ISSUE TITLE
can't change color of ions (?)

### ISSUE THREAD

**Issue by kailinguo24** [BradyAJohnston/MolecularNodes#254]
**Describe the bug**
Ions show up fuchsia in my renders, and I can't affect their color at all, even through the color by element options. 
**To Reproduce**
import a structure with ions in it, like 7r97
color by chains, use the normal cycles styles
you'll see some central fuchsia balls, and no matter what you do, their color will not change

**Expected behavior**
I wanted their color to be the same as the backbone I guess? 

**Screenshots**
These fuchsia balls are some of the ions: 
![image](https://github.com/BradyAJohnston/MolecularNodes/assets/116903309/df7eaadb-51dd-4891-92ad-f646c1e41e1f)
* I've already removed some of the ions, didn't realize there were more 

**Desktop (please complete the following information):**
 - Windows, x86 PC
 - Blender Version: 3.5
- MolecularNodes Version: 2.5.4

**Comment by BradyAJohnston** [comment]
These ions are being imported as ligands, as that must be how they are in the structure itself. 

These ones you are looking at seem to be magneisum ions. You _should_ be able to change the color of these by `Color by Element` but for whatever reason I can't figure out that isn't working.... which is very strange. This is definitely a bug and thanks for pointing it out!

`Color by Atomic Number` seems to work though for the magnesiusm.

![image](https://github.com/BradyAJohnston/MolecularNodes/assets/36021261/27300585-ec2b-431b-9b88-89861e2b82dd)

Because they have been labeleld as ligands, you can also use the ligand selection to deselect them in the final structure like this: 

![image](https://github.com/BradyAJohnston/MolecularNodes/assets/36021261/0c7a2fa2-c2cd-44d1-bd79-5cc5448d14f5)

**Comment by kailinguo24** [comment]
Great, thank you so much!

**Comment by PlethoraChutney** [comment]
As to why this is happening, the magenta color comes from a missed atomic number match. Opening the node group and playing with the `error_color, failed match` node changes these Mg ion colors and nothing else.

Interestingly, opening the cached `mmtf` file (saved by biotite within MN) in ChimeraX shows it doesn't have these Mg ions, nor does it have the Cl or HOH ligands. Weird!

**Comment by BradyAJohnston** [comment]
Hmmm that is an interesting observation. Something weird is happening, I haven't had a chance to look more closely into it. In theory the `Color by Element` and the `Color by Atomic Number` both use the same method under the hood, so I am unsure why it might be different.
