### ISSUE TITLE
"not alpha carbon" doesn't select non-alpha carbon

### ISSUE THREAD

**Issue by tubiana** [BradyAJohnston/MolecularNodes#26]
Hey :) 

It seems that "not alpha carbon" doesn't select non-alpha carbon on my example (here I remove all non-alpha carbon): 

https://user-images.githubusercontent.com/8037224/169951938-d6b82adb-70d3-4475-a377-317a18b490fa.mp4

**Comment by BradyAJohnston** [comment]
Also best currently to set the radius to 0 instead of deleting the geometry - to stop the atomic properties and their respective atoms from getting out of sync. In Blender 3.2 this will become less of a problem with Named Attributes, but until then it's best not to delete the points if at all possible, and just to set their radius to 0.

**Comment by BradyAJohnston** [comment]
Fixed in [v0.5.21](https://github.com/BradyAJohnston/MolecularNodes/releases/tag/v0.5.21)
