### ISSUE TITLE
Biological Assembly

### ISSUE THREAD

**Issue by MarcoAntonioBarreiros** [BradyAJohnston/MolecularNodes#263]
Hi, I have Molecular Nodes installed and running and besides Biological Assembly, everything is working fine. However, when I try to assemble a molecule I always got an error " can't detect Assembly data". I tried ti re-install it, change molecules, but nothing work. 

.

**Desktop (please complete the following information):**
 - OS:Windows
 - Hardware: Intel I5
 - Blender Version: 3.6.0
- MolecularNodes Version: 2.7.4

![molecularnodes](https://github.com/BradyAJohnston/MolecularNodes/assets/138163988/1240c4c8-d814-4583-b83c-81c4943274f2)

**Comment by PlethoraChutney** [comment]
Can you post the node tree you're using to assemble the molecule? I have it working fine with `1tnv`:

<img width="1432" alt="image" src="https://github.com/BradyAJohnston/MolecularNodes/assets/27385979/a02afc74-4948-4330-b07d-6d12927275ea">

**Comment by mwoldetensae** [comment]
I've been having the same problem. Haven't seen detected assemblies with files that are know to contain them. Regardless of where i place the assembly node, or what prep steps i take (selecting protein, changing to cycles, render view) i only seem to get a solid mash-up of the asymmetric unit. I've tried 1nd2, 1cd3 and 1tnv. 
Currently on Blender 3.5.1 because the same problem existed on Blender 3.6.
MolecularNode 2.7.4
Are there other required add-ons?
I'm new to Blender, so i might also be missing something simple.
![Screenshot ](https://github.com/BradyAJohnston/MolecularNodes/assets/60447531/ad257e38-0675-4d2f-9ac0-1e68107138c1)

**Comment by PlethoraChutney** [comment]
There aren't any other required add-ons, so it should be working alright. And your node tree works on my machine, but I've upgraded to Blender 3.6. I'll test it on a windows machine with your version of Blender when I get home, but I'd be surprised if that's the issue.

<img width="421" alt="image" src="https://github.com/BradyAJohnston/MolecularNodes/assets/27385979/6f250861-e80f-47b1-9c5a-d2f7fb2697f3">

<img width="787" alt="image" src="https://github.com/BradyAJohnston/MolecularNodes/assets/27385979/1052025b-e9fa-4090-bdca-1f95a59e24b8">

I did notice this error in the log: 
```
nodes.py:434: UserWarning: Gimbal lock detected. Setting third angle to zero since it is not possible to uniquely determine all angles.
  rotation = R.from_matrix(mat[:3, :3]).as_euler('xyz')
```

and a gimbal lock could result in bad transformations, but again, I'd expect behavior to be consistent across machines if that were the case.

# Something for you to try

What happens if you set `Scale Rotation` to 0, then step it up slowly to 1.0 (or higher) by clicking the little arrow on the slider? Is there any point along that curve where it looks right?

**Comment by mwoldetensae** [comment]
Thank you for your time & effort. 
Unfortunately setting the scale rotation from 0 to 1+ is just rotating the asymmetric unit in on itself.  

I wonder if this has anything to do with the Biotite problem you and Brady Johnston were troubleshooting on an earlier thread as i have yet to see any assemblies detected in the menu.  I'm not sure if the recommendation to change Cache save preferences was for you or for users though, I couldn't find anywhere to change those settings for the package, unless it requires coding it in. 
(Aside: I switched to MolecularNodes 2.7.3 a few days back and unless i'm mistaken, the packages from that version stuck around when i switched back to 2.7.4)

Again thank you both for this amazing product and i'm sorry for the hassle. I'm super excited to get it working. 
![Screenshot 2023-07-06 101228](https://github.com/BradyAJohnston/MolecularNodes/assets/60447531/467c2450-6f7a-41dd-9d13-5e9db64cf8da)

**Comment by PlethoraChutney** [comment]
I wouldn't worry about the cache --- it shouldn't be an issue for the version you've got.

This makes me think it's the gimbal lock. Our results look quite different for the same scaled rotation.

Could you please:
1. Set the `Scale Rotation` back to 1.0
2. Select `Instances` in the spreadsheet panel (upper-left in your image)
3. Scroll over to the `Rotations` column.

<img width="1451" alt="image" src="https://github.com/BradyAJohnston/MolecularNodes/assets/27385979/7fe5cfea-3020-4877-a195-291ca4a4d980">

**Comment by mwoldetensae** [comment]
Done
![Screenshot 2023-07-06 200428](https://github.com/BradyAJohnston/MolecularNodes/assets/60447531/5fd43a15-fea3-4134-a92b-c87e37abe700)

**Comment by BradyAJohnston** [comment]
@mwoldetensae it looks like it is likely an issue on import. When you import the asymmetric unit, ensure that you have `Centre Structure` unticked. The `Biological Assembly` node requires the original coordinates that are in the `.pdb` file, so you can't change the deposition of the structure at all until you apply the biological transformation node.

**Comment by mwoldetensae** [comment]
OH man! that worked! 
i know i prefer it centered, but I'm honestly surprised at my diligence in apparently checking that box in all the iterations I've been trying the past few days. 

Thank you both very much for the help! I'm sorry it wasn't a better use of your time. 
Would that i could buy you both a lifetime supply of coffee.

**Comment by BradyAJohnston** [comment]
No worries! I should be able to make it more robust in the future, but currently it just has to stay exactly where it is originally. Once you have created the assembly you can move it around as you wish though.
