### ISSUE TITLE
Optimize molecule class

### ISSUE THREAD

**Issue by kainszs** [BradyAJohnston/MolecularNodes#464]
As described in the issues #454 and #459, the molecule class can be optimized and unified with the AtomGroupInBlender class.

Goals:

- [x] clean up s. #454
- [x] write `molecule` class, with atomarraystruc as data object
- [x] write `molecule` class, with mda.atomgroup as data object
- [x] write `MoleculeInBlender` class

Further steps:
- test implementation
- optimize code, reduce redundancies
- integrate in code base

> Regarding the `Molecule` class. Currently when structures are imported, a 3D model is created inside of Blender. The idea is that the `Molecule` will contain information about the file that this model came from, and provide an interface that the user can change the associated style and edit the underlying information of the structure through this class. The currently existing python API isn't setup well for interacting with molecular structures, or changing the Geometry Nodes tress that are associated with the models. The class will hopefully provide a neater interface for loading, editing and styling the model, in a way that is nice to script with inside of a Jupyter Notebook or similar script.

_Originally posted by @BradyAJohnston in https://github.com/BradyAJohnston/MolecularNodes/issues/459#issuecomment-2028547718_

**Comment by kainszs** [comment]
@BradyAJohnston would you assign the issue to me?

**Comment by BradyAJohnston** [comment]
I just opened a PR with a new feature for 'live' MDA selection strings that update on each frame change in Blender #466 

This is the sort of thing that I envision for adding more connections between Blender and the MDA Universe underneath, to enable more user-friendly interaction with it.

**Comment by kainszs** [comment]
That looks very cool. How does the data twin (#455) play into this? I would also like to implement it. Because that fits in with the molecule class?

**Comment by rbdavid** [comment]
Firstly, my understanding of MN may be flawed so I defer to Brady. 

But, the `MoleculeInBlender` class you are describing is already implemented as the `bpy.types.Object` created from the `Molecule` object. This blender object has data associated with the structure stored in verts and edges associated with atoms and bonds. These verts/edges are used to draw the meshes seen in the Blender viewport. The (bio)physical/chemical information associated with verts/edges are stored as attributes. In my analogy to a "data twin", the Blender object is the visualization twin so adding a MN class for `MoleculeInBlender` isn't necessary. 

What I think deserves a bit more attention is dynamically updating/adding/deleting attributes based on (bio)physical/chemical information that is not feasibly implemented within a Blender object. The nature of attributes in Blender is fairly rigid as I understand it. For example, I want to visualize the solvation shell around an atom or molecule, which may change over a trajectory or when considering different atom selections. Blender attributes can't handle poorly-shaped data; really any data that does not fit into these [data types](https://docs.blender.org/manual/en/latest/modeling/geometry_nodes/attributes_reference.html#attribute-data-types). Instead, the "data twin" would be a data structure (in my opinion, a MDA Universe object) that _can_ access more complex biophysical information, such as atom selections based on distance or radius. Then, a simple Boolean attribute field can be added to the Blender object and geonodes can be used to visualize that attribute. Brady is already halfway there on this front with #466!

**Comment by kainszs** [comment]
Good morning,

Today I wanted to try my hand at unifying the AtomGroupInBlender class with the Molecule class. I noticed that the AtomGroup in MDA is very different from theAtomArrayStruc in Biotite. You want to strengthen the connection to MDA and include its analysis classes, would it be a possible option to write all the molecules we use in an MDA universe? 

Right now the data object of the molecule class is still an AtomArrayStruc. A universe seems more universal to me. So we would add the MDA functionality to each molecule.

**Comment by BradyAJohnston** [comment]
@kainszs Uniting import under a single parsing backend (all via MDAnalysis, rather than MDA / biotite), but MDAnalysis is missing some crucial functionality like reading `.cif / .bcif / .mmtf`, parsing biological assembly information and other general-purpose information from structure files. MDA is purpose-built for molecular dynamics trajectories, and biotite is a more general-purpose parser which gives access to secondary structure information / biological assembly information etc).

I don't think it would be possible to _truly_ merge the two, a static cystral structure is exactly that (static) while the MDA universe is intended for a trajectory that can play back and change over time.

There would be potential for parsing a structure with `biotite` and then manually building a `mda.Universe` with the correct information, but I don't know if that would be the right approach. 

I think the best approach would be altering / improving the MDA class implementation to better unify it with what ends up being the `Molecule` implementation. I think they should maybe still be different due to the different nature of the data underneath, but I'm sure they could share a lot of functionality.

**Comment by BradyAJohnston** [comment]
I'm wary of 'reinventing the wheel' though with this kind of approach at trying to unify them. It might be best just to be explicit that depending on the data type you are using, you interface with a completely different class and users can refer to documentation for biotite / MDA for technical implementations. 

Open to suggestions and feedback from others around what might be best

**Comment by BradyAJohnston** [comment]
The second suggestion to have a similar 'Molecule' class for the MDA data I can see working. I don't think we should try to convert one data format to the other, but unifying the inputs could certainly work like you suggest.

**Comment by kainszs** [comment]
If you like the idea, I would work out a proposal for the mda class.

Then we can see how things go from there.

**Comment by BradyAJohnston** [comment]
We aren't 'creating a scene', but Blender has a scene that scene that is always around, and is where the user is working. When the MDAnalysis session is loaded, it is appended to the scene, so that it is still accessible after the operator / function which created it is over. This allows for the session to be maintained and new coordinates to be updated as the frames changed.

A similar setup hasn't been a requirement for the static structures as most of the information is loaded into the scene in the form of 3D geometry, so the original files weren't required. It could still be useful to have a similar setup though, so that the `Molecule` class that is created can be maintained and can be accessed for different needs.

**Comment by kainszs** [comment]
Hi, 

I wasn't selected for GSoC, but would you like to pursue the idea further? Otherwise I will close the Issue.

Best regards
