### ISSUE TITLE
Falloff with MOL_Object_Effect

### ISSUE THREAD

**Issue by SanderEwen** [BradyAJohnston/MolecularNodes#59]
Hi Brady,

I'm trying the MOL_object_effect to delete atoms with the delete geometry node. As object I put in a cube, because I want a rectilinear removal of the atoms to make a intersection of a protein. However, when assigning the cube as an object, I'm getting a spherical removal of the atoms. Inside the MOL_object_effect I can't see how this spherical falloff is created, so I think it is inside the Python code somewhere (?). Can you help me how I can get a rectilinear falloff?

Thanks in advance! :)

Sander

**Comment by BradyAJohnston** [comment]
Hello! The MOL_object_effect just measures the distance from the center of the object, and uses that to drive the falloff. If you use a mesh cube and use the Geometry Proximity node and measure from the faces of the cube, you can use that to make it rectliniear falloff.

**Comment by SanderEwen** [comment]
Hi Brady,

Thank you for your message. I don't quite understand what you mean. I've tried different setups but to no avail. I currently have the following setup:

![image](https://user-images.githubusercontent.com/108576375/183264893-8fda30d1-fe5d-4a1f-bc5b-6e4e7e55308e.png)

If I put delete geometry on points the whole molecule disappears, if I put delete geometry on faces the molecule is present but the arrangement does not work. I also tried several changes to the node tree within the MOL_object_effect. Unfortunately, no setup works. Could you please help me in a little more detail?

Tnx again!

**Comment by BradyAJohnston** [comment]
Here is how you can use just the proximity from the faces to select atoms: 

![image](https://user-images.githubusercontent.com/36021261/183272632-adac3a55-8429-4a67-9d67-81668154607a.png)

Once atoms are inside the cube however they are are further from the sides so you can have to use an additional selection, you can measured the distance from the centre of the cube and combine the two booleans: 

![image](https://user-images.githubusercontent.com/36021261/183272669-f6fef3d8-b461-4766-b80e-da65a8b28229.png)

This will work less well as the box becomes more of an elongated rectange rather than a cube, but it should be enough to get you started and playing around hopefully :)

**Comment by SanderEwen** [comment]
Ahh...the atom selection...I didn't think of that. Thanks a lot for your help! I appreciate it. One coffee for you ;-)

**Comment by BradyAJohnston** [comment]
Thanks for the coffee! Leaving this issue open and labelling enhancement to track for improving the different selection & falloff nodes.
