### ISSUE TITLE
Render cartoon secondary structure

### ISSUE THREAD

**Issue by momeara** [BradyAJohnston/MolecularNodes#92]
Proteins have characteristic secondary structure (https://en.wikipedia.org/wiki/Protein_secondary_structure)

The PDB format has a section for specifying secondary structure (https://www.wwpdb.org/documentation/file-format-content/format23/sect5.html)

1) Parse the annotation to define atom properties
2) Define a Cartoon Style that shows alpha-helices, beta-sheets and loops similar to PyMOL, FoldIt, or Chimera.

**Comment by BradyAJohnston** [comment]
I've held off on implementing the secondary structure, as I wanted to try and have secondary structure detection be part of the nodes / Blender itself, so that a frame-by-frame secondary structure could be computed for molecular dynamics trajectories to visualise changes in secondary structure. 

This proving to likely to be to difficult, so I will be adding the SS that is pre-defined in the file and make that available to GN nodes for visualisation. 

How effectively the classic arrow style for the cartoon can be replicated inside of Geometry Nodes I am unsure, as I haven't really spent any time on it yet, but it's certainly on the list.

**Comment by momeara** [comment]
Glad to hear it's on the roadmap. 

Geometry nodes is fantastic, thanks for your work in putting it together!

**Comment by BradyAJohnston** [comment]
Thanks mate! I more immediately have a re-write of a bunch of the internals of the addon (as well as finishing writing my thesis ha) so unsure what sort of time frame we'd be looking at for it though.

**Comment by momeara** [comment]
If there's any way to briefly describe a strategy for implementation, it
might make for a good opportunity to invite a pull-request contribution.

**Comment by BradyAJohnston** [comment]
Party of why I am wanting to do the re-write as well: 
1. Make the code less of an embarrassing mess
2. Make it simpler for people to make contributions

Currently the addon is created with the help of another addon ([Serepens](https://blendermarket.com/products/serpens)) which was great for getting the addon up and running initially, but has made it difficult to accept pull requests / contributions. 

Did somebody mention technical debt?...

**Comment by momeara** [comment]
haha. Super impressive work non-the-less, and with the good first implementation it's clearer how the next design should be. 

I'm part of the Rosetta Commons--I'm sure a lot of folks are already or would be interested in your work. It might be nice to have you present somehow. Have you figured out what you're doing after you graduate? Would you be looking for a job or postdoc in protein modeling in the US?
